#!/bin/bash
set -Eexuo pipefail

cd ~/util/haskell-ide-engine

git fetch
git submodule update
git checkout "tags/$1"

stack ./install.hs hie-8.6.5
stack ./install.hs latest
stack ./install.hs data

# need hspec-discover on path https://github.com/haskell/haskell-ide-engine/issues/1500
# ensure it exists / is updated when we install / update HIE

stack config set resolver nightly
stack install hspec-discover