#!/bin/bash
set -Eexuo pipefail

TO_DOWNLOAD="https://github.com/cli/cli/releases/download/v$1/gh_$1_linux_amd64.deb"

TEMP_DEB="$(mktemp)" \
  && wget -O "$TEMP_DEB" $TO_DOWNLOAD \
  && sudo dpkg -i "$TEMP_DEB"

rm -f "$TEMP_DEB"
