#!/bin/bash
set -Eexuo pipefail

sudo curl -SL https://github.com/docker/compose/releases//latest/download/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose