#!/bin/bash
set -Eexuo pipefail

sudo apt install -y \
    libicu-dev \
    libtinfo-dev \
    libgmp-dev

sudo add-apt-repository -y ppa:hvr/ghc
sudo apt update
sudo apt install -y ghc-8.8.3 ghc-8.8.4 ghc-8.10.2 cabal-install-3.2

echo 'export PATH=$PATH:/opt/ghc/bin' >> $HOME/.profile

mkdir -p ~/.cabal/bin

echo 'export PATH=$PATH:$HOME/.cabal/bin' >> $HOME/.profile
