#!/bin/bash
set -Eexuo pipefail

sudo apt install -y \
    libicu-dev \
    libtinfo-dev \
    libgmp-dev

sudo add-apt-repository -y ppa:hvr/ghc
sudo apt update
sudo apt install -y ghc-8.6.5 ghc-8.8.1 cabal-install-3.0

echo 'export PATH=$PATH:/opt/ghc/bin' >> $HOME/.profile
