#!/bin/bash
set -Eexuo pipefail

export HIE_VERSION='1.0.0.0'

if [ ! -d ~/util/haskell-ide-engine ]; then
  git clone git@github.com:haskell/haskell-ide-engine.git --recursive ~/util/haskell-ide-engine
  update-hie $HIE_VERSION
fi
