#!/bin/bash
set -Eexuo pipefail

export HIE_VERSION='0.2'

if [ ! -d ~/util/haskell-language-server ]; then
  git clone git@github.com:haskell/haskell-language-server.git --recursive ~/util/haskell-language-server
  update-hls $HIE_VERSION
fi
