#!/bin/bash
set -Eexuo pipefail

if [ ! -f /usr/local/bin/stack ]; then
    wget -qO- https://get.haskellstack.org/ | sh

    echo 'export PATH=$PATH:$HOME/.local/bin' >> $HOME/.profile

    stack setup
fi
