#!/bin/bash
set -Eexuo pipefail

stack config set resolver lts

stack install hlint
stack install ghcid
stack install weeder

# stack install smuggler - not in stackage
# stack install ormolu - not in stackage https://github.com/tweag/ormolu/issues/412
# stack install hpack-convert - not building https://github.com/yamadapc/hpack-convert/issues/18
