#!/bin/bash
set -Eexuo pipefail

stack config set resolver lts

stack install hlint
stack install ghcid
stack install weeder
stack install stylish-haskell

# stack install smuggler - not in stackage
# stack install hpack-convert - not building https://github.com/yamadapc/hpack-convert/issues/18

# do I want? - hoogle, hpack
