#!/bin/bash
set -Eexuo pipefail

stack config set resolver nightly

stack install hlint
stack install ghcid
stack install weeder

# stack install smuggler - not in stackage
# stack install hpack-convert - not building https://github.com/yamadapc/hpack-convert/issues/18

# do I want? - stylish-haskell, hoogle, hpack
