#!/bin/bash
set -Eexuo pipefail

sudo apt install -y \
    libicu-dev \
    libtinfo-dev \
    libgmp-dev

export HIE_VERSION='0.12.0.0'

if [ ! -d ~/util/haskell-ide-engine ]; then
  git clone git@github.com:haskell/haskell-ide-engine.git --recursive ~/util/haskell-ide-engine
  update-hie $HIE_VERSION
fi
