#!/bin/bash
set -Eexuo pipefail

sudo snap install node --classic --channel=16/stable

if [ ! -d ~/.npm-global ]; then
  mkdir ~/.npm-global
  npm config set prefix '~/.npm-global'
  echo 'export PATH=~/.npm-global/bin:$PATH' >> $HOME/.profile
fi
