#!/bin/bash
set -Eexuo pipefail

sudo apt install -y hunspell-en-au

sudo snap install --classic atom

apm install \
  file-icons \
  language-docker \
  language-haskell \
  language-liquid \
  auto-update-plus \
  nix \
  language-pug
