#!/bin/bash
set -Eexuo pipefail

sudo apt install -y hunspell-en-au

sudo snap install --classic code

code --install-extension bbenoist.Nix
code --install-extension justusadam.language-haskell
code --install-extension haskell.haskell
code --install-extension ms-azuretools.vscode-docker
code --install-extension HashiCorp.terraform
code --install-extension GraphQL.vscode-graphql
code --install-extension dhall.dhall-lang
code --install-extension j-mueller.agda
code --install-extension banacorn.agda-mode
