#!/bin/bash
set -Eexuo pipefail

sudo apt install -y hunspell-en-au

sudo snap install --classic code

code --install-extension bbenoist.Nix
code --install-extension alanz.vscode-hie-server
code --install-extension ms-azuretools.vscode-docker
code --install-extension wholroyd.jinja
code --install-extension mauve.terraform
