#!/bin/bash
set -Eexuo pipefail

sudo apt install -y hunspell-en-au

sudo snap install --classic code

code --install-extension bbenoist.Nix
code --install-extension alanz.vscode-hie-server
code --install-extension peterjausovec.vscode-docker
code --install-extension ginfuru.vscode-jekyll-snippets
code --install-extension streetsidesoftware.code-spell-checker
