#!/bin/bash
set -Eexuo pipefail

sudo apt install -y libxcb-xtest0 libgl1-mesa-glx libxcb-xinerama0

TEMP_DEB="$(mktemp)" &&
wget -O "$TEMP_DEB" 'https://zoom.us/client/latest/zoom_amd64.deb' &&
sudo dpkg -i "$TEMP_DEB"
rm -f "$TEMP_DEB"
sudo apt -fy install
