#!/bin/bash
set -Eexuo pipefail

if [ ! -d ~/.bash_it ]; then
  git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
  ~/.bash_it/install.sh --silent
fi

# this clobbers github cli and I don't use it
echo 'unalias gh' >> $HOME/.bashrc
