#!/bin/bash
set -Eexuo pipefail

sudo apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# waiting for eoan packages https://github.com/docker/for-linux/issues/832
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   disco \
   stable"

sudo apt update

sudo apt install -y \
  docker-ce
