#!/bin/bash
set -Eexuo pipefail

sudo apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   eoan \
   stable"

# no docker releases for focal yet apparently https://github.com/docker/for-linux/issues/940#issuecomment-618591581

sudo apt update

sudo apt install -y \
  docker-ce \
  docker-ce-cli \
  containerd.io
