#!/bin/bash
set -Eexuo pipefail

sudo apt install -y \
    libicu-dev \
    libtinfo-dev \
    libgmp-dev


if [ ! -d ~/util/haskell-ide-engine ]; then
  git clone git@github.com:haskell/haskell-ide-engine.git --recursive ~/util/haskell-ide-engine
  cd ~/util/haskell-ide-engine
  make hie-8.4.4
  make build-doc-8.4.4
  make hie-8.6.3
  make build-doc-8.6.3
fi
