#!/bin/bash
set -Eexuo pipefail

curl -L https://nixos.org/nix/install | sh

. ~/.nix-profile/etc/profile.d/nix.sh

nix-channel --add https://nixos.org/channels/nixos-21.11 nixpkgs

ln -s ~/util/devbox/nixpkgs ~/.nixpkgs

nix-channel --update