#!/bin/bash
set -Eexuo pipefail

curl https://nixos.org/nix/install | sh

read -p "source ~/.nix-profile/etc/profile.d/nix.sh"

nix-channel --remove nixos-unstable

nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable

# geh how to make this work
cat "export NIX_PATH=$NIX_PATH:nixpkgs-unstable=$HOME/.nix-defexpr/channels/nixpkgs-unstable" >> $HOME/.profile

ln -s ~/util/devbox/nixpkgs ~/.nixpkgs

nix-channel --update

nix-env -i nix-dev-env
