#!/bin/bash
set -Eexuo pipefail

curl https://nixos.org/nix/install | sh

source ~/.profile

nix-channel --remove nixos-unstable

nix-channel --add https://nixos.org/channels/nixos-18.03 nixpkgs
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable

nix-channel --update

cat "export NIX_PATH=$NIX_PATH:nixpkgs-unstable=$HOME/.nix-defexpr/channels/nixpkgs-unstable" >> $HOME/.profile

ln -s ~/util/devbox/nixpkgs ~/.nixpkgs

nix-env -i nix-dev-env
