#!/bin/bash
set -Eexuo pipefail

cd $(dirname $0)/..

chmod +x ./path/*

ubuntu/setup

update-all

echo 'Docker:'
echo 'sudo usermod -aG docker $USER'

echo 'Bash it:'
echo 'bash-it enable alias git'
echo 'bash-it enable completion git'
echo 'bash-it enable completion docker'

echo 'Set git: git config --global user.email'

echo 'now relog'