#!/bin/bash
set -Eexuo pipefail

# We need to prefetch our sources since the nix build user doesn't have permission.
echo "Prefetching rea-as"
nix-prefetch-git \
    git@git.realestate.com.au:cowbell/rea-as.git \
    v1.3.4 \
    10ipnni2b68y36bxjnmy8y6jrrm26n1q84kl00pzsb19v4zjn9f7

echo "Installing rea-as"
nix-env -iA nixpkgs.rea-as

echo "Prefetching aws-console-url"
nix-prefetch-git \
    git@git.realestate.com.au:david-yeung/aws-console-url.git \
    v1.0.1 \
    1ck7385kckc7cz97ifnwpfngsvj4a78acygydnx57m7mzsvyhz07

echo "Installing aws-console-url"
nix-env -iA nixpkgs.aws-console-url

echo "Prefetching rea-slip-utils"
nix-prefetch-git \
    git@git.realestate.com.au:cowbell/rea-slip-utils.git \
    v1.1.0 \
    0bdw004w5z6vv53dpms7sv751wj0cg0zga4yisv31l5prlksj4pb

echo "Installing rea-slip-utils"
nix-env -iA nixpkgs.rea-slip-utils

echo "Done."
