#!/bin/bash
set -Eexuo pipefail

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SYNC_NAME="aws-shortcuts" \
    SYNC_REPO=git@git.realestate.com.au:resi-lob/aws-shortcuts.git \
    SYNC_REF=c141defe4b565fc280552bc8f6f403d77eeec1c1 \
    SYNC_TARGET_DIR=$HOME/.aws-shortcuts \
    ${SOURCE_DIR}/scripts/sync-git-repo

export REA_LDAP_USER=alistair.burrowes
export AWS_DEFAULT_REGION=ap-southeast-2

rea-as saml > ~/.aws-shortcuts/iam-roles.txt

echo 'source ~/.aws-shortcuts/aws-shortcuts.sh' >> ~/.bashrc
